### ISSUE TITLE
WIP what's this all about?

### ISSUE THREAD

**Issue by cjayb** [meeg-cfin/introduction_to_git#1]
Key points:

* Motivation for using version
* How does git work:
    * add/commit
    * branches
* How does GitHub work and why use it?:
    * remote repos
    * sharing code

Program:

1. Intro/refresher on command line
2. Intro to git
3. Intro to GitHub.

**Comment by cjayb** [comment]
Run away? Me?! Never! @MadsJensen 

Here we go, how's this for brainstorming, @britta-wstnr ?!

**Comment by britta-wstnr** [comment]
Perfect :) Thanks @cjayb

**Comment by MadsJensen** [comment]
+1 @cjayb 

@britta-wstnr  cannot do a git/GitHub and develop it on GH ;)

**Comment by britta-wstnr** [comment]
@MadsJensen fair enough :smile: 

Obviously, we should also have a section "undoing things" (git reset, incl. comparing commits, etc.) -- I'll just edit your list @cjayb ?

**Comment by MadsJensen** [comment]
Hi, I have added a programme.md to make the development of the programme a bit more git-like ;) 

We should also decide on a time for workshop.

**Comment by britta-wstnr** [comment]
Closing - it's done! :tada:
