### ISSUE TITLE
materials and methods

### ISSUE THREAD

**Issue by cjayb** [meeg-cfin/introduction_to_git#3]
# We need a demo git workflow!

## Quick-and-dirty: work directly on `master`

* demo basic usage here

## 'Feature branch'-way

* introduce branches

## Exercise

* short text file ('poem'), with hard line breaks
* modify (how?) the text, use git to track
* talk about transfer to code...

## Installing Git (customising)

* set up a github account (before course)
* set username and email

## Choose your favourite text editor

* Why do I need one, what's a text editor?
* Linux: use `gedit`

## Prerequisites

* read notebooks on CLI
* make sure you have
  * a linux/mac laptop, __OR__
  * a win laptop with remote desktop access to `hyades` (__VPN account needed!!!__)

## Adding vs. committing

* staging, commits, files
* once I commit, is it online?
* making more changes, committing them
* reverting/going back in time

# Additional reading

* [git book](git-scm.com)

**Comment by britta-wstnr** [comment]
Closing - I think we managed to cover most of it :smile:
